name: cbnew-auto-push

on:
  schedule:
    # 每工作日9:00执行，转为UTC要减8小时，实际会延迟几十分钟左右 1
    - cron: '30 1 * * 1-5'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
          ref: master

    - name: Run cbnew push job
      run: |
        cd bin
        chmod 773 cbnew
        ./cbnew -barkkey=${{ secrets.MY_BARK_KEY }}
        ./cbnew -barkkey=${{ secrets.JINS_SECRET_KEY }}
        ./cbnew -barkkey=${{ secrets.HUS_SECRET_KEY }}
